# Generated by Django 4.1.2 on 2022-11-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_userdetailsmodel_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsmodel',
            name='user_server',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
    ]
